# Generated by Django 5.1.1 on 2024-12-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customergender',
            table='customer_genders',
        ),
    ]
