# Generated by Django 5.1.1 on 2025-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_cart_items_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building_name',
            field=models.CharField(blank=True, default=None, max_length=196, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=196, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Singapore', max_length=196),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_first_name',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_last_name',
            field=models.CharField(default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=196, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=' ', max_length=196),
        ),
        migrations.AddField(
            model_name='order',
            name='street_optional',
            field=models.CharField(blank=True, default=None, max_length=196, null=True),
        ),
    ]
