# Generated by Django 5.1.1 on 2025-01-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('code', models.SlugField(unique=True, allow_unicode=True)),
                ('short_description', models.CharField(max_length=160)),
                ('default', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='static/img/brands/no-image.jpg', null=True, upload_to='static/img/brands/')),
            ],
            options={
                'db_table': 'product_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('code', models.SlugField(unique=True, allow_unicode=True)),
                ('short_description', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('code', models.SlugField(unique=True, allow_unicode=True)),
                ('short_description', models.CharField(max_length=160)),
                ('default', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='static/img/categories/no-image.jpg', null=True, upload_to='static/img/categories/')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory')),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('slug', models.SlugField(unique=True, allow_unicode=True)),
                ('short_description', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productbrand')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('themes', models.ManyToManyField(to='products.theme')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=196)),
                ('url', models.ImageField(blank=True, default='static/img/products/no-image.jpg', null=True, upload_to='static/img/products/')),
                ('is_main_image', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
