# Generated by Django 5.1.1 on 2025-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, default='static/img/product-reviews/no-image.jpg', null=True, upload_to='static/img/product-reviews/'),
        ),
    ]
