# Generated by Django 5.1.1 on 2025-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='sentiment',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
