# Generated by Django 5.1.1 on 2025-01-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='sentiment_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
