# Generated by Django 5.1.1 on 2025-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='sentiment_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
